import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { altbestandZuordnen, bestellungMerken, filialeAendern } from '../../src/data/filialen.js'
import { inventurStarten, leereInventur, produktSpeichern } from '../../src/data/inventur.js'
const key = 'paarfuss.react.v1'
const alt = { produkte: [{ artikelnummer: 'FC-1', barcode: '4006381333931', name: 'Creme', bestand: 2, mindestbestand: 5, zielbestand: 12, packung: 6, einheit: 'Flasche' }], inventur: leereInventur() }
const basis = () => filialeAendern(altbestandZuordnen(alt, 'innsbruck'), 'kematen', d => produktSpeichern(d, { ...d.produkte[0], bestand: 20, mindestbestand: 3, zielbestand: 8 }, 'FC-1'))
const bestellt = () => bestellungMerken(basis(), { produktId: 'FC-1', filiale: 'innsbruck', anzahl: 12, datum: '2026-09-30' }, 'B1')
const nav = (page, name) => page.getByRole('navigation').getByRole('button', { name, exact: true })
const karte = page => page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Creme · Innsbruck', exact: true }) })
async function start(page, daten = basis()) {
  await page.goto('/')
  await page.evaluate(({ key, daten }) => localStorage.setItem(key, JSON.stringify(daten)), { key, daten })
  await page.reload()
}
const browserFehler = new WeakMap()
test.beforeEach(async ({ page }) => {
  browserFehler.set(page, [])
  page.on('pageerror', error => browserFehler.get(page).push(error.message))
})
test.afterEach(async ({ page }) => { expect(browserFehler.get(page)).toEqual([]) })

test('Altbestand erfordert bewusste Filialwahl und bleibt bis dahin unberührt', async ({ page }) => {
  await start(page, alt)
  await expect(page.getByRole('button', { name: 'Bestand zuordnen', exact: true })).toBeDisabled()
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)), key)).toEqual(alt)
  await page.getByLabel('Filiale des bisherigen Bestands').selectOption('kematen')
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Bestand zuordnen', exact: true }).click()
  await expect(page.getByLabel('Aktive Filiale')).toHaveValue('kematen')
  await nav(page, 'Lager').click()
  await expect(page.getByRole('article')).toContainText('Bestand: 2')
  await page.getByLabel('Aktive Filiale').selectOption('innsbruck')
  await expect(page.getByRole('article')).toContainText('Bestand: 0')
})
test('Filialwechsel trennt Buchungen und setzt ungespeicherte Formulare zurück', async ({ page }) => {
  await start(page)
  await nav(page, 'Lager').click()
  await page.getByRole('button', { name: 'Bearbeiten', exact: true }).click()
  await page.getByLabel('Produktname', { exact: true }).fill('Ungespeichert')
  await page.getByLabel('Aktive Filiale').selectOption('kematen')
  await expect(page.getByRole('heading', { name: 'Lager · Kematen', exact: true })).toBeVisible()
  await expect(page.getByLabel('Produktname', { exact: true })).toHaveValue('')
  await page.getByLabel('Barcode manuell eingeben').fill('4006381333931')
  await page.getByRole('button', { name: 'Wareneingang buchen', exact: true }).click()
  await expect(page.getByRole('article')).toContainText('Bestand: 21')
  await page.reload()
  await expect(page.getByLabel('Aktive Filiale')).toHaveValue('kematen')
  await page.getByLabel('Aktive Filiale').selectOption('innsbruck')
  await nav(page, 'Lager').click()
  await expect(page.getByRole('article')).toContainText('Bestand: 2')
})
test('Bestellvermerk, Teillieferung und Reststorno erhalten beide Bestände korrekt', async ({ page }) => {
  await start(page)
  await nav(page, 'Nachbestellen').click()
  const artikel = karte(page)
  await expect(artikel).toContainText('Noch nachbestellen: 12 Flasche')
  await expect(artikel).toContainText('Kematen hat 12 Flasche über dem Zielbestand')
  await artikel.getByText('Externe Bestellung vermerken', { exact: true }).click()
  await artikel.getByRole('button', { name: 'Als bestellt vermerken' }).click()
  await expect(artikel).toContainText('Noch nachbestellen: 0 Flasche')
  await expect(artikel).toContainText('Bestand: 2')
  await artikel.getByLabel('Jetzt geliefert (Flasche)').fill('5')
  page.once('dialog', d => d.accept())
  await artikel.getByRole('button', { name: 'Lieferung buchen', exact: true }).click()
  await expect(artikel).toContainText('5 geliefert · 7 offen')
  await expect(artikel).toContainText('Bestand: 7')
  await page.reload()
  await nav(page, 'Nachbestellen').click()
  await expect(artikel).toContainText('5 geliefert · 7 offen')
  page.once('dialog', d => d.accept())
  await artikel.getByRole('button', { name: 'Rest stornieren' }).click()
  await expect(artikel).toHaveCount(0)
  const daten = await page.evaluate(key => JSON.parse(localStorage.getItem(key)), key)
  expect(daten.produkte[0].lager.innsbruck.bestand).toBe(7)
  expect(daten.produkte[0].lager.kematen.bestand).toBe(20)
  expect(daten.bestellungen[0].storniert).toBe(true)
})
test('offene Bestellung wird nicht zusätzlich per Scanner gebucht', async ({ page }) => {
  await start(page, bestellt())
  await nav(page, 'Lager').click()
  await page.getByLabel('Barcode manuell eingeben').fill('4006381333931')
  await page.getByRole('button', { name: 'Wareneingang buchen', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('unter Nachbestellen buchen')
  await expect(page.getByRole('article')).toContainText('Bestand: 2')
})
test('Speicherfehler lässt Teilwareneingang vollständig unverändert', async ({ page }) => {
  await start(page, bestellt())
  await nav(page, 'Nachbestellen').click()
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('Speicher voll') } })
  await karte(page).getByLabel('Jetzt geliefert (Flasche)').fill('3')
  page.once('dialog', d => d.accept())
  await karte(page).getByRole('button', { name: 'Lieferung buchen', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Speicher voll')
  await expect(karte(page)).toContainText('Bestand: 2')
  await expect(karte(page)).toContainText('0 geliefert · 12 offen')
})
test('Umlagerung bucht beide Filialen gemeinsam', async ({ page }) => {
  await start(page)
  await page.getByLabel('Aktive Filiale').selectOption('kematen')
  await nav(page, 'Lager').click()
  await page.getByText('Ware in die andere Filiale umlagern', { exact: true }).click()
  await page.getByLabel('Umlagermenge (Flasche)').fill('6')
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Nach Innsbruck umlagern' }).click()
  await expect(page.getByRole('article')).toContainText('Bestand: 14')
  await page.getByLabel('Aktive Filiale').selectOption('innsbruck')
  await expect(page.getByRole('article')).toContainText('Bestand: 8')
})
test('Nachbestellfilter und Druckansicht zeigen die gewählte Filiale ohne Bedienelemente', async ({ page }) => {
  let d = basis()
  d = filialeAendern(d, 'kematen', s => produktSpeichern(s, { ...s.produkte[0], bestand: 1 }, 'FC-1'))
  await start(page, d)
  await nav(page, 'Nachbestellen').click()
  await expect(page.getByRole('article')).toHaveCount(2)
  await page.getByLabel('Filiale filtern').selectOption('kematen')
  await expect(page.getByRole('article')).toHaveCount(1)
  await expect(page.getByRole('article')).toContainText('Creme · Kematen')
  await page.emulateMedia({ media: 'print' })
  await expect(page.getByRole('navigation')).toBeHidden()
  await expect(page.getByLabel('Aktive Filiale')).toBeHidden()
  await expect(page.getByRole('button', { name: 'Liste drucken / als PDF sichern' })).toBeHidden()
  await expect(page.getByText('Externe Bestellung vermerken', { exact: true })).toBeHidden()
  await expect(page.getByRole('heading', { name: 'Creme · Kematen', exact: true })).toBeVisible()
})
test('Sicherung unter Einstellungen enthält beide Lager, Inventuren und Bestellungen', async ({ page }) => {
  const daten = filialeAendern(bestellt(), 'kematen', inventurStarten)
  await start(page, daten)
  await nav(page, 'Start').click()
  await expect(page.getByRole('button', { name: 'Daten exportieren', exact: true })).toHaveCount(0)
  await nav(page, 'Einstellungen').click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Daten exportieren', exact: true }).click()
  const datei = await download
  const sicherung = JSON.parse(await readFile(await datei.path(), 'utf8'))
  expect(sicherung).toEqual(daten)
  await page.getByLabel('JSON-Sicherung importieren').setInputFiles({ name: 'filialen.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(sicherung)) })
  await expect(page.getByLabel('Filiale des importierten Bestands')).toHaveCount(0)
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Daten ersetzen', exact: true }).click()
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)), key)).toEqual(daten)
})
test('mobile Nachbestellliste passt einschließlich Bestell- und Lieferformular', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await start(page, bestellt())
  await nav(page, 'Nachbestellen').click()
  await karte(page).getByText('Externe Bestellung vermerken', { exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/nachbestellen-mobil.png', fullPage: true })
})
test('offenes Bearbeitungsformular überschreibt keine zwischenzeitliche Buchung', async ({ page }) => {
  await start(page)
  await nav(page, 'Lager').click()
  await page.getByRole('button', { name: 'Bearbeiten', exact: true }).click()
  await page.getByRole('button', { name: 'Creme: Bestand erhöhen' }).click()
  await page.getByLabel('Produktname', { exact: true }).fill('Neuer Name')
  await page.getByRole('button', { name: 'Produkt speichern', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('während der Bearbeitung geändert')
  await expect(page.getByRole('article')).toContainText('Bestand: 3')
  await expect(page.getByRole('article').getByRole('heading', { name: 'Creme', exact: true })).toBeVisible()
})
